### ISSUE TITLE
Allow forbiding `math/rand` usage

### ISSUE THREAD

**Issue by mx-psi** [OpenPeeDeeP/depguard#101]
`math/rand` has a `v2` version, `math/rand/v2`, announced here: https://go.dev/blog/randv2. It would be useful if depguard would allow forbiding usage of `math/rand` but allowing the usage of `math/rand/v2`. Is this supported? Would there be any way to do that today?

**Comment by lithammer** [comment]
This configuration should work. This trick is the `$` which means exact match rather than prefix match.

```jsonc
{
  // ...
  "deny": {
    "$math/rand": "Use math/rand/v2 instead of math/rand",
  },
  // ...
}
```

**Comment by mx-psi** [comment]
Ah. thanks! Didn't realize this feature existed :)

**Comment by rittneje** [comment]
It should be `"math/rand$"` not `"$math/rand"`.
