### ISSUE TITLE
could not resolve host go install

### ISSUE THREAD

**Issue by maikelmclauflin** [OpenPeeDeeP/depguard#11]
```
go: github.com/OpenPeeDeeP/depguard@v0.0.0-20180806142446-a69c782687b2: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/95001b568ac43a1c1353717a884bfe2c209a6976254cb2f59fb2d5a473159b78: exit status 128:
	fatal: unable to access 'https://github.com/OpenPeeDeeP/depguard/': Could not resolve host: github.com
```
not sure what else i can say. here's the repo that i'm installing: 

https://github.com/brave-intl/bat-go

**Comment by dixonwille** [comment]
I am unsure how to help you with this. This isn't depguard specific. It means your go install was unable to resolve `github.com`. I do not own `github.com`. 

If you are on linux/mac you can try `dig github.com` to see if you get an IP address back. `ping github.com` will also tell you if it can resolve to an IP and hit the servers.
