### ISSUE TITLE
whitelist + blacklist

### ISSUE THREAD

**Issue by pierrre** [OpenPeeDeeP/depguard#16]
I'm maintaining a large number of Go project at my company.
I'm using depguard through golangci-lint.

Currently, my depguard config is a blacklist.
I don't want that some developers start to use `unsafe` or `reflect` packages.

My problem: I also want to have control over which third party packages are imported in my projects.
Some developers are importing libraries without any control:
- the dependency has not been approved
- the library is not maintained/buggy
- the feature is already provided by another imported library
- we're using only 1% of the feature of the imported library
- etc

My goal:
- allow a list of third party packages, 
- disallow some packages from the stdlib
- allows other stdlib packages

Is it possible ?
Does it make sense ? Or am I using depguard incorrectly ?

**Comment by dixonwille** [comment]
It feels strange for two different types of lists to control the packages. But I do think a V2 of depguard is in order from other issues in this repository. I understand what you are trying to accomplish but logically I can't compare against a blacklist and whitelist at the same time...

If a package isn't in the whitelist but it is in blacklist, then whitelist picks it first as it isn't in there... That is where it is difficult to do what you are asking.

**Comment by pierrre** [comment]
I have a design idea:
- allow to match packages with wildcard (e.g. `github.com/myorganization/*`)
- add a package alias `std` that matches all stdlib packages

If in `blacklist` mode, the listed packages are rejected, the others are accepted.

If in `whitelist` mode, the listed packages are accepted, the others are rejected.

In in `mixed` mode (match the first condition):
- the blacklisted packages are rejected
- the whitelisted packages are accepted
- the other packages are rejected

My config would be:
- blacklisted: reflect, unsafe
- accepted: std, github.com/myorganization/*

WDYT ?

**Comment by dixonwille** [comment]
In mixed, is where you have both blacklisted and other rejected. Why not just but the list of go packages in whitelist you do want? just because it is a long list?

**Comment by pierrre** [comment]
Yes, it's a long list:
- I want to allow all packages from stdlib, except some dangerous ones (unsafe and reflect)
- I want to allow all packages from my organization (e.g. github.com/myorganization/*), but maybe it's already possible

**Comment by pierrre** [comment]
PS: I don't want to maintain/update a list of packages from stdlib

**Comment by dixonwille** [comment]
This will be getting tagged in V2. Not just the allow and deny but also the variables (`$gostd` for packages and `$test` and `$all` for files).
