### ISSUE TITLE
Update to use x/tools/go/analysis 

### ISSUE THREAD

**Issue by ldez** [OpenPeeDeeP/depguard#26]
Hello,

The project still uses the deprecated `golang.org/x/tools/go/loader` instead of `golang.org/x/tools/go/analysis`.

https://github.com/golang/tools/blob/587a15310bddfc939d37cfaa8be8ea4c3808c3f1/go/loader/doc.go#L10-L11

Do you plan to migrate to `golang.org/x/tools/go/analysis`?
Do you need help?

**Comment by dixonwille** [comment]
Help is always welcome. I no longer use this tool as the stack I work in daily no longer includes Go :( If I can find the time I will take look into it.

**Comment by dixonwille** [comment]
https://github.com/OpenPeeDeeP/depguard/blob/feature/v2/v2/depguard.go started working on it. While digging into it, it was not a backwards compatible change. So I figured out I need to start looking at a V2 variant. Will be defining exactly what that means later this week. Feel free to offer ideas here until I create a V2 issue, milestone, etc.

**Comment by dixonwille** [comment]
So I have a working beta `v2.0.0-beta.2`

```sh
go install github.com/OpenPeeDeeP/depguard/v2/cmd/depguard@v2.0.0-beta.2
```

I have tested on a few repositories. But would like others to try it out to.

**Comment by dixonwille** [comment]
I have just released version 2
