### ISSUE TITLE
depguard: create analyzer: couldn't expand $gostd: could not read GOROOT directory

### ISSUE THREAD

**Issue by hidu** [OpenPeeDeeP/depguard#46]
1. build golangci-lint on computer A but execute it on computer B
2. computer B without $GOROOT env value，but has other go version

**Comment by adamdecaf** [comment]
The error can be reproduced by using a GOROOT other than what the binary was built with. (Computer A vs Computer B) 

You can resolve the issue by faking the runtime GOROOT to match the builders GOROOT. 

Example: https://github.com/golangci/golangci-lint/issues/3862#issuecomment-1572853232 

More Info: https://github.com/golangci/golangci-lint/issues/3862#issuecomment-1572792248

**Comment by dixonwille** [comment]
Tagged new commit with PR that should fix this.
