### ISSUE TITLE
Update README with information on Allow/Deny List functionality

### ISSUE THREAD

**Issue by dixonwille** [OpenPeeDeeP/depguard#55]
It is unclear what an empty allow and deny list do. README should reflect this.

**Comment by ianlewis** [comment]
Currently it seems with `golangci-lint` 1.53+ that an empty `allow` (e.g. no `depguard` config) means that nothing is allowed. Pretty sure that changed from 1.52 as we didn't encounter errors before.

**Comment by dixonwille** [comment]
https://github.com/OpenPeeDeeP/depguard/issues/49

Yes the default behavior changed. Having no depguard config, but enabling it did absolutely nothing in depguard v1.

**Comment by maqdev** [comment]
Is there a way to allow everything by default, and only deny what's in deny list? Removing `allow` section doesn't help.

**Comment by dixonwille** [comment]
https://github.com/OpenPeeDeeP/depguard/pull/70

I believe this is what you are looking for. I still want to document it before merging it in.
